import{a as q,S as v,i as p}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const y=40,E="53049514-dee19204cd3e9e15730e86423",M=q.create({baseURL:"https://pixabay.com/api/",params:{key:E,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y}});async function m(e,r=1){const{data:a}=await M.get("",{params:{q:e,page:r}});return a}const h=document.querySelector("#gallery"),g=document.querySelector("#loader");let $=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(e){const r=e.map(R).join("");h.insertAdjacentHTML("beforeend",r),$.refresh()}function P(){h.innerHTML=""}function w(){g.hidden=!1}function L(){g.hidden=!0}function S(e){p.info({message:e,position:"topRight"})}function A(e){p.success({message:e,position:"topRight"})}function f(e){p.error({message:e,position:"topRight"})}function O(){const e=h.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}function R({webformatURL:e,largeImageURL:r,tags:a,likes:c,views:t,comments:o,downloads:s}){return`
<li class="photo-card">
  <a href="${r}" class="gallery__link">
    <img src="${e}" alt="${a}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${c}</p>
    <p><b>Views</b> ${t}</p>
    <p><b>Comments</b> ${o}</p>
    <p><b>Downloads</b> ${s}</p>
  </div>
</li>`}const d={form:document.querySelector("#search-form"),input:document.querySelector('#search-form [name="query"]'),gallery:document.querySelector("#gallery"),loadMore:document.querySelector("#load-more")};let l="",i=1,n=0;d.form.addEventListener("submit",_);d.loadMore.addEventListener("click",H);async function _(e){if(e.preventDefault(),l=d.input.value.trim(),!l){S("Enter a search term");return}i=1,n=0,P(),u(!1),w();try{const r=await m(l,i);if(n=r.totalHits,!n){f("Sorry, no images match your search query.");return}b(r.hits),A(`Hooray! We found ${n} images.`),i*y<n&&u(!0)}catch(r){console.error(r),f("Something went wrong, try again later.")}finally{L()}}async function H(){i+=1,u(!1),w();try{const e=await m(l,i);b(e.hits),i*y>=n?S("We're sorry, but you've reached the end of search results."):u(!0),O()}catch(e){console.error(e),f("Something went wrong, try again later.")}finally{L()}}function u(e){d.loadMore.hidden=!e}
//# sourceMappingURL=index.js.map
